version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=chaapy
      - POSTGRES_PASSWORD=12345chaapy
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql11/data
      - ./data/init-scripts.sql:/docker-entrypoint-initdb.d/scripts.sql

volumes:
  db:
    driver: local